/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package code;

import java.awt.Color;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author XPC
 */
public class panelReportes extends javax.swing.JPanel {

    Conexion conn = new Conexion();
    Connection reg = conn.getConexion();
    FuncionesReportes funcionesReportes = new FuncionesReportes();
    

    /**
     * Creates new form panelReportes
     */
    public panelReportes() {
        initComponents();

        // PlaceHolders
        PlaceHolder nombreREstd = new PlaceHolder("Ingrese nombre del archivo txt", nombreArchivoEstd);
        PlaceHolder nombreRCursos = new PlaceHolder("Ingrese nombre del archivo txt", nombreArchivoCursos);
        try {
            funcionesReportes.estudiantesActivos();
            funcionesReportes.cursosActivos();
        } catch (SQLException ex) {
            Logger.getLogger(panelReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estudiantes = new javax.swing.JPanel();
        labelActivosE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cantidadEstudiantes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelActivosC = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantidadCursos = new javax.swing.JLabel();
        rpEstudiantes = new javax.swing.JPanel();
        estd = new javax.swing.JLabel();
        rpCursos = new javax.swing.JPanel();
        cursos = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        porcentajeMod = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        prsCantidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        virCantidad = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelEdad = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        promedioEdad = new javax.swing.JLabel();
        nombreArchivoEstd = new javax.swing.JTextField();
        nombreArchivoCursos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estudiantes.setBackground(new java.awt.Color(204, 204, 204));
        estudiantes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        estudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                estudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                estudiantesMouseExited(evt);
            }
        });
        estudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelActivosE.setBackground(new java.awt.Color(0, 0, 0));
        labelActivosE.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelActivosE.setText("Estudiantes Activos");
        estudiantes.add(labelActivosE, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/users.png"))); // NOI18N
        estudiantes.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 24, 24));

        cantidadEstudiantes.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantidadEstudiantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadEstudiantes.setText("0");
        estudiantes.add(cantidadEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        add(estudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 100));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelActivosC.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelActivosC.setText("Cursos Activos");
        jPanel1.add(labelActivosC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/courses2.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 24, 24));

        cantidadCursos.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantidadCursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantidadCursos.setText("0");
        jPanel1.add(cantidadCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 300, 100));

        rpEstudiantes.setBackground(new java.awt.Color(18, 90, 173));
        rpEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rpEstudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rpEstudiantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rpEstudiantesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rpEstudiantesMousePressed(evt);
            }
        });
        rpEstudiantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estd.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        estd.setForeground(new java.awt.Color(255, 255, 255));
        estd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        estd.setText("Generar Reporte");
        rpEstudiantes.add(estd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        add(rpEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 130, 30));

        rpCursos.setBackground(new java.awt.Color(18, 90, 173));
        rpCursos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rpCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rpCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rpCursosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rpCursosMousePressed(evt);
            }
        });
        rpCursos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cursos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cursos.setForeground(new java.awt.Color(255, 255, 255));
        cursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cursos.setText("Generar Reporte");
        rpCursos.add(cursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 30));

        add(rpCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 130, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porcentajeMod.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        porcentajeMod.setText("Modalidades Activas");
        jPanel2.add(porcentajeMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mod.png"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 24, 24));

        prsCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prsCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prsCantidad.setText("0");
        jPanel2.add(prsCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Vir");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Prs");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        virCantidad.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        virCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        virCantidad.setText("0");
        jPanel2.add(virCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 300, 100));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEdad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelEdad.setText("Promedio De Edad");
        jPanel3.add(labelEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/age.png"))); // NOI18N
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 24, 24));

        promedioEdad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        promedioEdad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        promedioEdad.setText("0");
        jPanel3.add(promedioEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, 100));

        nombreArchivoEstd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArchivoEstdActionPerformed(evt);
            }
        });
        add(nombreArchivoEstd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 170, 30));

        nombreArchivoCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreArchivoCursosActionPerformed(evt);
            }
        });
        add(nombreArchivoCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 170, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Descargar reporte de estudiantes");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Descargar reporte de cursos");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void rpEstudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpEstudiantesMouseEntered
        rpEstudiantes.setBackground(new Color(21, 101, 192));
    }//GEN-LAST:event_rpEstudiantesMouseEntered

    private void rpEstudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpEstudiantesMouseExited
        rpEstudiantes.setBackground(new Color(18, 90, 173));
    }//GEN-LAST:event_rpEstudiantesMouseExited

    private void rpEstudiantesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpEstudiantesMousePressed
        // archivo txt
        funcionesReportes.archivoEstudiantes();
    }//GEN-LAST:event_rpEstudiantesMousePressed

    private void rpCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpCursosMouseEntered
        rpCursos.setBackground(new Color(21, 101, 192));
    }//GEN-LAST:event_rpCursosMouseEntered

    private void rpCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpCursosMouseExited
        rpCursos.setBackground(new Color(18, 90, 173));
    }//GEN-LAST:event_rpCursosMouseExited

    private void rpCursosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rpCursosMousePressed
        // archivo txt
        funcionesReportes.archivoCursos();
    }//GEN-LAST:event_rpCursosMousePressed

    private void estudiantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesMouseEntered
        estudiantes.setBackground(new Color(197, 168, 14));
        labelActivosE.setForeground(Color.white);
    }//GEN-LAST:event_estudiantesMouseEntered

    private void estudiantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estudiantesMouseExited
        estudiantes.setBackground(new Color(204, 204, 204));
        labelActivosE.setForeground(Color.black);
    }//GEN-LAST:event_estudiantesMouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(197, 168, 14));
        labelEdad.setForeground(Color.white);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(new Color(204, 204, 204));
        labelEdad.setForeground(Color.black);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(new Color(197, 168, 14));
        labelActivosC.setForeground(Color.white);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(204, 204, 204));
        labelActivosC.setForeground(Color.black);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        jPanel2.setBackground(new Color(197, 168, 14));
        porcentajeMod.setForeground(Color.white);
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        jPanel2.setBackground(new Color(204, 204, 204));
        porcentajeMod.setForeground(Color.black);
    }//GEN-LAST:event_jPanel2MouseExited

    private void nombreArchivoEstdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArchivoEstdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArchivoEstdActionPerformed

    private void nombreArchivoCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreArchivoCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreArchivoCursosActionPerformed

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel cantidadCursos;
    public static javax.swing.JLabel cantidadEstudiantes;
    private javax.swing.JLabel cursos;
    private javax.swing.JLabel estd;
    private javax.swing.JPanel estudiantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelActivosC;
    private javax.swing.JLabel labelActivosE;
    private javax.swing.JLabel labelEdad;
    public static javax.swing.JTextField nombreArchivoCursos;
    public static javax.swing.JTextField nombreArchivoEstd;
    private javax.swing.JLabel porcentajeMod;
    public static javax.swing.JLabel promedioEdad;
    public static javax.swing.JLabel prsCantidad;
    private javax.swing.JPanel rpCursos;
    private javax.swing.JPanel rpEstudiantes;
    public static javax.swing.JLabel virCantidad;
    // End of variables declaration//GEN-END:variables
}
