/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package code;

import java.awt.Color;

/**
 *
 * @author XPC
 */
public class panelInfo extends javax.swing.JPanel {

    /**
     * Creates new form panelInfo
     */
    public panelInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprin = new javax.swing.JPanel();
        rolando = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Andy = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Fabian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Andres = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Kevin = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Infodecadauno = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(680, 360));

        panelprin.setBackground(new java.awt.Color(255, 255, 255));
        panelprin.setPreferredSize(new java.awt.Dimension(680, 360));
        panelprin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rolando.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rolando.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rolando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rolandoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rolandoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Rolando");

        javax.swing.GroupLayout rolandoLayout = new javax.swing.GroupLayout(rolando);
        rolando.setLayout(rolandoLayout);
        rolandoLayout.setHorizontalGroup(
            rolandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );
        rolandoLayout.setVerticalGroup(
            rolandoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelprin.add(rolando, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, -1));

        Andy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Andy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Andy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AndyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AndyMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Andy");

        javax.swing.GroupLayout AndyLayout = new javax.swing.GroupLayout(Andy);
        Andy.setLayout(AndyLayout);
        AndyLayout.setHorizontalGroup(
            AndyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        AndyLayout.setVerticalGroup(
            AndyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelprin.add(Andy, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 143, -1));

        Fabian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Fabian.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Fabian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FabianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FabianMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Fabian");

        javax.swing.GroupLayout FabianLayout = new javax.swing.GroupLayout(Fabian);
        Fabian.setLayout(FabianLayout);
        FabianLayout.setHorizontalGroup(
            FabianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        FabianLayout.setVerticalGroup(
            FabianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelprin.add(Fabian, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 143, -1));

        Andres.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Andres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Andres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AndresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AndresMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Andres");

        javax.swing.GroupLayout AndresLayout = new javax.swing.GroupLayout(Andres);
        Andres.setLayout(AndresLayout);
        AndresLayout.setHorizontalGroup(
            AndresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        AndresLayout.setVerticalGroup(
            AndresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelprin.add(Andres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 143, -1));

        Kevin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Kevin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Kevin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KevinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                KevinMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Kevin");

        javax.swing.GroupLayout KevinLayout = new javax.swing.GroupLayout(Kevin);
        Kevin.setLayout(KevinLayout);
        KevinLayout.setHorizontalGroup(
            KevinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );
        KevinLayout.setVerticalGroup(
            KevinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        panelprin.add(Kevin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 143, -1));

        Infodecadauno.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout InfodecadaunoLayout = new javax.swing.GroupLayout(Infodecadauno);
        Infodecadauno.setLayout(InfodecadaunoLayout);
        InfodecadaunoLayout.setHorizontalGroup(
            InfodecadaunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );
        InfodecadaunoLayout.setVerticalGroup(
            InfodecadaunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        panelprin.add(Infodecadauno, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 10, 390, 350));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        panelprin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 10, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rolandoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolandoMouseEntered
     rolando.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_rolandoMouseEntered

    private void rolandoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rolandoMouseExited
     rolando.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_rolandoMouseExited

    private void AndyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AndyMouseEntered
      Andy.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_AndyMouseEntered

    private void AndyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AndyMouseExited
     Andy.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_AndyMouseExited

    private void FabianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabianMouseEntered
        Fabian.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_FabianMouseEntered

    private void FabianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FabianMouseExited
         Fabian.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_FabianMouseExited

    private void AndresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AndresMouseEntered
       Andres.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_AndresMouseEntered

    private void AndresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AndresMouseExited
       Andres.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_AndresMouseExited

    private void KevinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KevinMouseEntered
       Kevin.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_KevinMouseEntered

    private void KevinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KevinMouseExited
        Kevin.setBackground(new Color(0,0,204));
    }//GEN-LAST:event_KevinMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Andres;
    private javax.swing.JPanel Andy;
    private javax.swing.JPanel Fabian;
    private javax.swing.JPanel Infodecadauno;
    private javax.swing.JPanel Kevin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panelprin;
    private javax.swing.JPanel rolando;
    // End of variables declaration//GEN-END:variables
}
