/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package code;

import static code.Main.panelContenido;
import static code.panelCursos.idCursoModificar;
import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author XPC
 */
public class panelRegistroEstudiantes extends javax.swing.JPanel {

    public static String cu = null;
    FuncionesEstudiante funcionesR = new FuncionesEstudiante();
    public static DefaultComboBoxModel modeloCursos = new DefaultComboBoxModel();

    public panelRegistroEstudiantes() {
        initComponents();
        modeloCursos.removeAllElements();

        // Placeholders
        PlaceHolder nombre = new PlaceHolder("Ingresar nombre", inputNombre);
        PlaceHolder pApellido = new PlaceHolder("Ingresar primer apellido", inputPrimerApellido);
        PlaceHolder sApellido = new PlaceHolder("Ingresar segundo apellido", inputSegundoApellido);
        PlaceHolder edad = new PlaceHolder("Ingresar edad", inputEdad);
        PlaceHolder ced = new PlaceHolder("Ingresar cédula", inputCedula);
        PlaceHolder tel = new PlaceHolder("Ingresar número telefónico", inputTelefono);

        try {
            funcionesR.getListaCursos();
        } catch (NullPointerException ex) {
            Logger.getLogger(panelRegistroEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        etiquetaTitulo = new javax.swing.JLabel();
        etiquetaNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        etiquetaPrimerApellido = new javax.swing.JLabel();
        inputPrimerApellido = new javax.swing.JTextField();
        etiquetaSegundoApellido = new javax.swing.JLabel();
        inputSegundoApellido = new javax.swing.JTextField();
        etiquetaEdad = new javax.swing.JLabel();
        inputEdad = new javax.swing.JTextField();
        etiquetaCedula = new javax.swing.JLabel();
        inputCedula = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        etiquetaTelefono = new javax.swing.JLabel();
        inputTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JPanel();
        etiquetaGuardar = new javax.swing.JLabel();
        etiquetaCurso = new javax.swing.JLabel();
        listaCursos = new javax.swing.JComboBox<>();

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setPreferredSize(new java.awt.Dimension(680, 360));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiquetaTitulo.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        panel1.add(etiquetaTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        etiquetaNombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaNombre.setText("Nombre");
        panel1.add(etiquetaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        inputNombre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        inputNombre.setNextFocusableComponent(inputPrimerApellido);
        inputNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputNombreMousePressed(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        inputNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNombreKeyPressed(evt);
            }
        });
        panel1.add(inputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 30));

        etiquetaPrimerApellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaPrimerApellido.setText("Primer Apellido");
        panel1.add(etiquetaPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        inputPrimerApellido.setNextFocusableComponent(inputSegundoApellido);
        inputPrimerApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputPrimerApellidoMousePressed(evt);
            }
        });
        panel1.add(inputPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 190, 30));

        etiquetaSegundoApellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaSegundoApellido.setText("Segundo Apellido");
        panel1.add(etiquetaSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        inputSegundoApellido.setNextFocusableComponent(inputEdad);
        inputSegundoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputSegundoApellidoMousePressed(evt);
            }
        });
        panel1.add(inputSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 30));

        etiquetaEdad.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaEdad.setText("Edad");
        panel1.add(etiquetaEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        inputEdad.setNextFocusableComponent(inputCedula);
        inputEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputEdadMousePressed(evt);
            }
        });
        panel1.add(inputEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 95, 30));

        etiquetaCedula.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaCedula.setText("Cédula");
        panel1.add(etiquetaCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        inputCedula.setNextFocusableComponent(inputTelefono);
        inputCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputCedulaMousePressed(evt);
            }
        });
        panel1.add(inputCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 190, 30));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        panel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 10, 350));

        etiquetaTelefono.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaTelefono.setText("Teléfono");
        panel1.add(etiquetaTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        inputTelefono.setNextFocusableComponent(listaCursos);
        inputTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputTelefonoMousePressed(evt);
            }
        });
        panel1.add(inputTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 190, 30));

        btnGuardar.setBackground(new java.awt.Color(18, 90, 173));
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGuardarMousePressed(evt);
            }
        });

        etiquetaGuardar.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        etiquetaGuardar.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaGuardar.setNextFocusableComponent(inputNombre);

        javax.swing.GroupLayout btnGuardarLayout = new javax.swing.GroupLayout(btnGuardar);
        btnGuardar.setLayout(btnGuardarLayout);
        btnGuardarLayout.setHorizontalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        btnGuardarLayout.setVerticalGroup(
            btnGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnGuardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 210, 50));

        etiquetaCurso.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        etiquetaCurso.setText("Curso");
        panel1.add(etiquetaCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        listaCursos.setModel(modeloCursos);
        listaCursos.setNextFocusableComponent(etiquetaGuardar);
        panel1.add(listaCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreActionPerformed

    private void btnGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMousePressed
        funcionesR.guardarDatosRegistroE();
    }//GEN-LAST:event_btnGuardarMousePressed
    /*Autor : Andy*/
    private void inputNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputNombreMousePressed


    }//GEN-LAST:event_inputNombreMousePressed
    /*Autor :Andy*/
    private void inputPrimerApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPrimerApellidoMousePressed

    }//GEN-LAST:event_inputPrimerApellidoMousePressed
    /*Autor : Andy*/
    private void inputSegundoApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSegundoApellidoMousePressed

    }//GEN-LAST:event_inputSegundoApellidoMousePressed
    /*Autor : Andy*/
    private void inputEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputEdadMousePressed


    }//GEN-LAST:event_inputEdadMousePressed
    /*Autor : Andy*/
    private void inputCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputCedulaMousePressed


    }//GEN-LAST:event_inputCedulaMousePressed
    /*Autor : Andy*/
    private void inputTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputTelefonoMousePressed

    }//GEN-LAST:event_inputTelefonoMousePressed

    private void inputNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNombreKeyPressed

    }//GEN-LAST:event_inputNombreKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnGuardar;
    private javax.swing.JLabel etiquetaCedula;
    private javax.swing.JLabel etiquetaCurso;
    private javax.swing.JLabel etiquetaEdad;
    public static javax.swing.JLabel etiquetaGuardar;
    private javax.swing.JLabel etiquetaNombre;
    private javax.swing.JLabel etiquetaPrimerApellido;
    private javax.swing.JLabel etiquetaSegundoApellido;
    private javax.swing.JLabel etiquetaTelefono;
    public javax.swing.JLabel etiquetaTitulo;
    public static javax.swing.JTextField inputCedula;
    public static javax.swing.JTextField inputEdad;
    public static javax.swing.JTextField inputNombre;
    public static javax.swing.JTextField inputPrimerApellido;
    public static javax.swing.JTextField inputSegundoApellido;
    public static javax.swing.JTextField inputTelefono;
    private javax.swing.JSeparator jSeparator3;
    public static javax.swing.JComboBox<String> listaCursos;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
