/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package code;

import static code.Home.panelContenido;
import java.sql.Connection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sojo
 */
public class panelEstudiantes extends javax.swing.JPanel {
    Conexion conn;
    Connection reg;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    
    public panelEstudiantes() {
        //llenarModelo();
        initComponents();
        conn = new Conexion();
        reg = conn.getConexion();
        try {
            getStudents();
        } catch (SQLException ex) {
            Logger.getLogger(panelEstudiantes.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        panelContenido.removeAll();
        panelContenido.add(this);
        panelContenido.revalidate();
        panelContenido.repaint();
        */
    }
    
    public void llenarModelo() {
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Primer Apellido");
        modeloTabla.addColumn("Segundo Apellido");
        modeloTabla.addColumn("Edad");
        modeloTabla.addColumn("Cédula");
        modeloTabla.addColumn("Teléfono");
        /*
        String a[] = {"Fabián", "Sojo", "Mejías", "19", "118740180", "87947110"};
        modeloTabla.addRow(a);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        Image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiantes = new javax.swing.JTable();
        btnAgregar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        Title.setText("Estudiantes");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        tablaEstudiantes.setModel(modeloTabla);
        jScrollPane1.setViewportView(tablaEstudiantes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, 240));

        btnAgregar.setBackground(new java.awt.Color(18, 90, 173));
        btnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAgregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAgregarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAgregarMousePressed(evt);
            }
        });
        btnAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Agregar");
        btnAgregar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 80, 30));

        btnModificar.setBackground(new java.awt.Color(18, 90, 173));
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnModificarMousePressed(evt);
            }
        });
        btnModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificar");
        btnModificar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        jPanel1.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 80, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 360, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMousePressed
        System.out.println("Hola");
        // Instanciamos el panel
        panelRegistroEstudiantes rAg = new panelRegistroEstudiantes();
        rAg.setSize(680, 360);
        rAg.setLocation(0, 0);
        rAg.etiquetaTitulo.setText("Registrar Estudiante");
        rAg.etiquetaGuardar.setText("Registrar");
        
        
        // Removemos el panel anterior y pasamos el nuevo para mostrarlo
        
        panelContenido.removeAll();
        panelContenido.add(rAg);
        panelContenido.revalidate();
        panelContenido.repaint();
        
    }//GEN-LAST:event_btnAgregarMousePressed

    private void btnAgregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseEntered

    }//GEN-LAST:event_btnAgregarMouseEntered

    private void btnAgregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseExited
 
    }//GEN-LAST:event_btnAgregarMouseExited

    private void btnModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMousePressed
        System.out.println("Hola");
        // Instanciamos el panel
        panelRegistroEstudiantes rUp = new panelRegistroEstudiantes();
        rUp.setSize(680, 360);
        rUp.setLocation(0, 0);
        rUp.etiquetaTitulo.setText("Modificar Estudiante");
        rUp.etiquetaGuardar.setText("Modificar");
        
        // Removemos el panel anterior y pasamos el nuevo para mostrarlo
        
        panelContenido.removeAll();
        panelContenido.add(rUp);
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_btnModificarMousePressed

    private void btnModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseEntered

    }//GEN-LAST:event_btnModificarMouseEntered

    private void btnModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseExited
   
    }//GEN-LAST:event_btnModificarMouseExited

    private void getStudents() throws SQLException{
        Statement stm = reg.createStatement();
        ResultSet counter = stm.executeQuery("SELECT * FROM `estudiantes`");
        
        // para obtener el numero de filas
        int contador = 0;
        while(counter.next()) {
            contador++;
        }
        
        String estudiantes[][] = new String[contador][6]; // [filas][columnas]
        int i = 0; // itera las filas
        ResultSet re = stm.executeQuery("SELECT * FROM `estudiantes`");
        while(re.next()){
            estudiantes[i][0] = re.getString("nombre");
            estudiantes[i][1] = re.getString("primerApellido");
            estudiantes[i][2] = re.getString("segundoApellido");
            estudiantes[i][3] = re.getString("edad");
            estudiantes[i][4] = re.getString("cedula");
            estudiantes[i][5] = re.getString("telefono");
            i++;
        }
        
        tablaEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
        estudiantes,
        new String [] {
            "Nombre", "Primer Apellido", "Segundo Apellido", "Edad", "Cédula", "Teléfono"
        }));
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Image;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btnAgregar;
    private javax.swing.JPanel btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEstudiantes;
    // End of variables declaration//GEN-END:variables
}
